In [1]:
import numpy
from matplotlib import pyplot

In [2]:
myarray = numpy.linspace(0, 5, 10)
print(myarray)

[ 0.          0.55555556  1.11111111  1.66666667  2.22222222  2.77777778
  3.33333333  3.88888889  4.44444444  5.        ]


In [3]:
myarray = linspace(0, 5, 10)

NameError: name 'linspace' is not defined

In [4]:
a=5
b='five'
c=5.0

In [5]:
type(a)

int

In [6]:
type(b)

str

In [7]:
type(c)

float

In [8]:
14/a

2.8

In [9]:
14/c

2.8

In [10]:
for i in range(5):
    print("hi\n")

hi

hi

hi

hi

hi



In [11]:
for i in range(3):
    for j in range(3):
        print(i,j)
        
    print("this statment is within the i-loop, but not the j-loop")

0 0
0 1
0 2
this statment is within the i-loop, but not the j-loop
1 0
1 1
1 2
this statment is within the i-loop, but not the j-loop
2 0
2 1
2 2
this statment is within the i-loop, but not the j-loop


In [12]:
myvals=numpy.array([1,2,3,4,5])
myvals

array([1, 2, 3, 4, 5])

In [13]:
myvals[0], myvals[4]

(1, 5)

In [14]:
myvals[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [15]:
myvals[0:3]

array([1, 2, 3])

In [16]:
a=numpy.linspace(1,5,5)

In [17]:
a

array([ 1.,  2.,  3.,  4.,  5.])

In [18]:
a[2]=17

In [19]:
a

array([  1.,   2.,  17.,   4.,   5.])

In [20]:
c=a.copy()

In [21]:
a[2]=3

In [22]:
a

array([ 1.,  2.,  3.,  4.,  5.])

In [23]:
c

array([  1.,   2.,  17.,   4.,   5.])

In [24]:
from IPython.display import YouTubeVideo
YouTubeVideo('vWkb7vahaXQ')